name = "Trapezoid"
uuid = "54ea0a13-c7c2-4df0-924a-d4e052cc338d"
version = "0.1.0"
authors = ["binado <bernardopveronese@gmail.com>"]

[compat]
julia = "1.12"

[extras]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "ForwardDiff"]
