[workspace]
projects = ["CumulativeIntegrals", "Cosmology", "AstroSGWB", "AstroSGWBInference", "CBCDistributions", "notebooks"]

[deps]
AstroSGWB = "6a24b920-6d62-45b7-87dc-84df6f794d62"
AstroSGWBInference = "17b6d0b6-80a1-4842-aa05-e7535ef3d247"
CBCDistributions = "04d2795f-0c6c-4919-9dae-19f280fe5e84"
Cosmology = "2d447719-857e-46c1-9a42-11db63d1a3c6"
CumulativeIntegrals = "d5e3e301-3204-4776-a62d-278416b3d314"

[extras]
AstroSGWB = "6a24b920-6d62-45b7-87dc-84df6f794d62"
AstroSGWBInference = "17b6d0b6-80a1-4842-aa05-e7535ef3d247"
CBCDistributions = "04d2795f-0c6c-4919-9dae-19f280fe5e84"
Cosmology = "2d447719-857e-46c1-9a42-11db63d1a3c6"
CumulativeIntegrals = "d5e3e301-3204-4776-a62d-278416b3d314"

[sources]
AstroSGWB = {path = "AstroSGWB"}
AstroSGWBInference = {path = "AstroSGWBInference"}
CBCDistributions = {path = "CBCDistributions"}
Cosmology = {path = "Cosmology"}
CumulativeIntegrals = {path = "CumulativeIntegrals"}
