cache_path = "../analysis_numpyro_julia_cache.h5"
detectors = ["S1", "R1"]
sample_only = ["H0"]
seed = 1

output_dir = "../logs/smoke"
output_prefix = "smoke"

[init]
H0 = 67.66
"Ωm" = 0.3096
"Ξ₀" = 1.0
"Ξₙ" = 1.91
"γ" = 2.7
"κ" = 5.7
zpeak = 2.0

[sampler]
n_samples = 200
n_adapts = 100
target_acceptance = 0.8
num_chains = 2
checkpoint_every = 50
