#!/usr/bin/env bash
set -euo pipefail

CONFIG_DIR="${1:?usage: scripts/submit_mcmc_array.sh <config-dir> [max-parallel]}"
MAX_PARALLEL="${2:-8}"

if [[ ! -d "$CONFIG_DIR" ]]; then
    echo "config directory does not exist: $CONFIG_DIR" >&2
    exit 2
fi

if [[ ! "$MAX_PARALLEL" =~ ^[1-9][0-9]*$ ]]; then
    echo "max-parallel must be a positive integer; got: $MAX_PARALLEL" >&2
    exit 2
fi

CONFIGS=()
while IFS= read -r config; do
    CONFIGS+=("$config")
done < <(find "$CONFIG_DIR" -maxdepth 1 -type f -name '*.toml' | sort)
NCONFIGS="${#CONFIGS[@]}"

if (( NCONFIGS == 0 )); then
    echo "no .toml configs found in $CONFIG_DIR" >&2
    exit 2
fi

CONFIG_ARRAY_LITERAL=$(printf '    %q\n' "${CONFIGS[@]}")

mkdir -p logs

sbatch --array="0-$((NCONFIGS - 1))%${MAX_PARALLEL}" <<SBATCH
#!/bin/bash
#SBATCH --job-name=astrosgwb-mcmc
#SBATCH --output=logs/%x-%A_%a.out
#SBATCH --error=logs/%x-%A_%a.err
#SBATCH --time=24:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=32G

# Headless AstroSGWB NUTS job array. One config file == one array task.
#
# Generated by:
#   scripts/submit_mcmc_array.sh $CONFIG_DIR $MAX_PARALLEL

set -euo pipefail

CONFIGS=(
$CONFIG_ARRAY_LITERAL
)

TASK_ID="\${SLURM_ARRAY_TASK_ID:?submit_mcmc_array.sh requires --array}"
if (( TASK_ID < 0 || TASK_ID >= \${#CONFIGS[@]} )); then
    echo "array task \$TASK_ID out of range for \${#CONFIGS[@]} configs" >&2
    exit 2
fi
CONFIG="\${CONFIGS[\$TASK_ID]}"

# Slurm executes a copied batch script from its spool directory on some
# clusters, so BASH_SOURCE/dirname can point at /var/spool/slurmd. Anchor all
# relative paths to the directory where sbatch was submitted.
REPO_ROOT="\${SLURM_SUBMIT_DIR:-\$PWD}"
cd "\$REPO_ROOT"
mkdir -p logs

if [[ ! -d AstroSGWB || ! -d AstroSGWBInference || ! -f scripts/run_mcmc.jl ]]; then
    echo "submit_mcmc_array.sh must be submitted from the AstroSGWB.jl repository root" >&2
    echo "current directory: \$PWD" >&2
    exit 2
fi

if [[ ! -f "\$CONFIG" ]]; then
    echo "config file does not exist: \$CONFIG" >&2
    exit 2
fi

# Adjust this to your cluster's module system / Julia install.
# module load julia/1.12

# Locate the raw Julia binary to bypass the juliaup config lock issue on HPC.
JULIA_EXE=\$(ls -d "\$HOME"/.julia/juliaup/julia-*/bin/julia 2>/dev/null | sort -V | tail -n 1 || echo "julia")

# Each Julia thread runs one MCMC chain.
export JULIA_NUM_THREADS="\${SLURM_CPUS_PER_TASK:-1}"
# Keep BLAS single-threaded; the runner also enforces this.
export OPENBLAS_NUM_THREADS=1
export INPUT="*"
export OUTPUT="*"

# Set up a node-local depot to avoid file-locking contention on shared filesystems (NFS/Lustre).
# Julia will read from ~/.julia but write any temporary/architecture cache to the local SSD.
if [[ -n "\${SLURM_TMPDIR:-}" ]]; then
    export JULIA_DEPOT_PATH="\$SLURM_TMPDIR/julia_depot:\$HOME/.julia"
else
    export JULIA_DEPOT_PATH="/tmp/\$USER/julia_depot:\$HOME/.julia"
fi
mkdir -p "\${JULIA_DEPOT_PATH%%:*}"

echo "[submit_mcmc_array] task=\$TASK_ID config=\$CONFIG julia=\$JULIA_EXE threads=\$JULIA_NUM_THREADS depot=\${JULIA_DEPOT_PATH%%:*}"

# NOTE: Do NOT run Pkg.instantiate() on compute nodes.
# Instead, ensure you run \`just setup-run\` on the login node BEFORE submitting.
#
# julia --project=scripts/run -e 'using Pkg; Pkg.instantiate()'

# Run the MCMC sampler.
job-nanny "\$JULIA_EXE" --project=scripts/run -t "\$JULIA_NUM_THREADS" \\
    scripts/run_mcmc.jl "\$CONFIG"
SBATCH
