name: CI

on:
  push:
    branches:
      - main
      - master
    tags: ['*']
  pull_request:

permissions:
  actions: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.12'
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v6
      - uses: julia-actions/setup-julia@v3
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v3
      # Skip julia-buildpkg: AstroSGWBInference/deps/build.jl runs PackageCompiler
      # create_app (intended for `just build`, not CI). Pkg.test() is enough here.
      - uses: julia-actions/julia-runtest@v1
        with:
          project: AstroSGWB
          coverage: false
      - uses: julia-actions/julia-runtest@v1
        with:
          project: AstroSGWBInference
          coverage: false
